version: 1.0.{build}
image: Visual Studio 2019
clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%

    git checkout -qf %APPVEYOR_REPO_COMMIT%

    git submodule update --init --recursive
environment:
  NugetKey:
    secure: HHX4vqalpwoxP6o3nQQzKo3VzEuS9D+1clYE/US2SQnC+obre7IxRdtj9xsPV9TX
  CoverallRepoToken:
    secure: iWrJHFXHi7Ovfr2rEwUy1qCX50XisIZGunCaFMHQUJnqpuu1aBoALjjEEvtQNGag
  BotToken:
    secure: PmtGSlRIDP4Ew76A1ouTv6RExmiuXWnoezbSr3BPKxA=
  SonarToken:
    secure: p1Sh9zz6U5bIjQ7rB9JEHlY2vlZZJzU8eHwg1lQPiMf3cJQfzH3h4FXxrAE7LOfm
build_script:
- set JAVA_HOME=C:\Program Files\Java\jdk11
- ps: .\build.ps1 --branch $env:APPVEYOR_REPO_BRANCH --buildCounter $env:APPVEYOR_BUILD_NUMBER --gitHash $env:APPVEYOR_REPO_COMMIT --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE
test: off